services:
  gestorfinanceiro:
    image: ${DOCKER_REGISTRY-}gestorfinanceiro
    build:
      context: .
      dockerfile: GestorFinanceiro/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db # Garante que o banco de dados inicie primeiro

  db:
    image: postgres:latest
    container_name: gestorfinanceiro_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gestor}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gestor123}
      POSTGRES_DB: ${POSTGRES_DB:-gestorfinanceiro}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data: